{
 "title": "Air Quality",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Temperatura", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 20, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"Temperatura\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AirQuality\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"tempBMP\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"ESP8266\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Temperatura maksymalna",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Temperatura\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AirQuality\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"tempBMP\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"ESP8266\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "Temperatura minimalna",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Temperatura\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AirQuality\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"tempBMP\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"ESP8266\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "Temperatura aktualna",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Temperatura\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AirQuality\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"tempBMP\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"ESP8266\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> yield(name: \"max\")"
    }
   ]
  },
  { "title": "Wilgotność", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 20, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"Temperatura\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AirQuality\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"humDHT\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"ESP8266\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Wilgotność maksymalna",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Temperatura\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AirQuality\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"humDHT\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"ESP8266\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "Wilgotność minimalna",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Temperatura\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AirQuality\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"humDHT\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"ESP8266\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "Wilgotność aktualna",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Temperatura\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AirQuality\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"humDHT\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"ESP8266\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> yield(name: \"max\")"
    }
   ]
  },
  { "title": "Ciśnienie", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 20, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "query": "from(bucket: \"Temperatura\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AirQuality\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pressBMP\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"ESP8266\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Ciśnienie maksymalne",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Temperatura\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AirQuality\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pressBMP\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"ESP8266\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "Ciśnienie minimalne",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Temperatura\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AirQuality\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pressBMP\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"ESP8266\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "Ciśnienie aktualne",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Temperatura\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AirQuality\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pressBMP\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"ESP8266\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> yield(name: \"max\")"
    }
   ]
  },
  { "title": "Lotne Związki Organiczne", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 20, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"Temperatura\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AirQuality\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vocSGP40\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield()"
    }
   ]
  },
  { "title": "Algorytm LZO", "type": "canvas", "gridPos": { "h": 12, "w": 4, "x": 20, "y": 40 } },
  { "title": "Pyły Zawieszone PM1 PM2,5 PM10", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Pyły Zawieszone PM1",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "query": "from(bucket: \"Temperatura\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AirQuality\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pm1\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"ESP8266\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Średnia PM1",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Temperatura\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AirQuality\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pm1\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"ESP8266\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Maksimum PM1",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Temperatura\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AirQuality\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pm1\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"ESP8266\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Pyły Zawieszone PM2,5",
   "type": "timeseries",
   "description": "Średnie dobowe dopuszczalne stężenie PM2,5 wynosi 25  μg/m3.",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "query": "from(bucket: \"Temperatura\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AirQuality\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pm2.5\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"ESP8266\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Średnia PM2,5",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Temperatura\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AirQuality\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pm2.5\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"ESP8266\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Maksimum PM2,5",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Temperatura\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AirQuality\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pm2.5\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"ESP8266\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Pyły Zawieszone PM10",
   "type": "timeseries",
   "description": "Średnie dobowe dopuszczalne stężenie PM10 wynosi 50  μg/m3.",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "query": "from(bucket: \"Temperatura\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AirQuality\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pm10\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"ESP8266\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Średnia PM10",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Temperatura\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AirQuality\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pm10\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"ESP8266\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Maksimum PM10",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Temperatura\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AirQuality\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pm10\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"ESP8266\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}